### ISSUE TITLE
Round 1: Do not repeat user(s) that were guessed correctly on subsequent tries

### ISSUE THREAD

**Issue by aureliaspecker** [aureliaspecker/twitter-guess-who#10]
```
You got 1 correct: @user1
Would you like to retry for 1 point? y
OK, so which number corresponds to:

@user1
@user2 
@user3 
@user4 
@user5 

```
@user1 was guessed correctly the first time and so it shouldn't be shown on the second try

**Comment by dormrod** [comment]
Can you check this works now please @aureliaspecker ?

**Comment by aureliaspecker** [comment]
Nice one. But I would also remove the numbered options to choose from with each new round.
